[project]
name = "catmat"
version = "0.1.0"
description = "Projeto para busca de catmat com base no descritivo do produto ou serviço que o usuário esteja procurando"
authors = [
    {name = "Jonatha W."}
]
license = "GNU GPL V3"
requires-python = ">3.14,<4.0"
dependencies = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "sqlalchemy[asyncio] (>=2.0.54,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "alembic (>=1.20.0,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "typer (>=0.27.0,<0.28.0)"
]

[project.scripts]
catmat-etl = "catmat.etl.cli:app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
