"""create catalog tables

Revision ID: 124e6804b003
Revises: 
Create Date: 2026-09-17 09:08:30.331896

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '124e6804b003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_natures',
    sa.Column('expense_nature_code', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('expense_nature_name', sa.String(length=255), nullable=True),
    sa.Column('expense_nature_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('expense_nature_code', name=op.f('pk_expense_natures'))
    )
    op.create_table('groups',
    sa.Column('group_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_status', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_code', name=op.f('pk_groups'))
    )
    op.create_table('classes',
    sa.Column('class_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_code', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('class_status', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['groups.group_code'], name=op.f('fk_classes_group_code_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_code', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_group_code'), 'classes', ['group_code'], unique=False)
    op.create_table('pdms',
    sa.Column('pdm_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('class_code', sa.Integer(), nullable=False),
    sa.Column('pdm_name', sa.String(length=255), nullable=False),
    sa.Column('pdm_status', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_code'], ['classes.class_code'], name=op.f('fk_pdms_class_code_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pdm_code', name=op.f('pk_pdms'))
    )
    op.create_index(op.f('ix_pdms_class_code'), 'pdms', ['class_code'], unique=False)
    op.create_table('items',
    sa.Column('item_code', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('pdm_code', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('item_status', sa.Boolean(), nullable=False),
    sa.Column('is_sustainable', sa.Boolean(), nullable=False),
    sa.Column('ncm_code', sa.String(length=20), nullable=True),
    sa.Column('ncm_description', sa.Text(), nullable=True),
    sa.Column('applies_preference_margin', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdm_code'], ['pdms.pdm_code'], name=op.f('fk_items_pdm_code_pdms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_code', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_pdm_code'), 'items', ['pdm_code'], unique=False)
    op.create_index('ix_items_status_active', 'items', ['item_status'], unique=False, postgresql_where=sa.text('item_status'))
    op.create_table('pdm_expense_natures',
    sa.Column('pdm_code', sa.Integer(), nullable=False),
    sa.Column('expense_nature_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['expense_nature_code'], ['expense_natures.expense_nature_code'], name=op.f('fk_pdm_expense_natures_expense_nature_code_expense_natures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pdm_code'], ['pdms.pdm_code'], name=op.f('fk_pdm_expense_natures_pdm_code_pdms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pdm_code', 'expense_nature_code', name=op.f('pk_pdm_expense_natures'))
    )
    op.create_index(op.f('ix_pdm_expense_natures_expense_nature_code'), 'pdm_expense_natures', ['expense_nature_code'], unique=False)
    op.create_table('supply_units',
    sa.Column('pdm_code', sa.Integer(), nullable=False),
    sa.Column('supply_unit_sequence', sa.Integer(), nullable=False),
    sa.Column('supply_unit_acronym', sa.String(length=50), nullable=True),
    sa.Column('supply_unit_name', sa.String(length=255), nullable=True),
    sa.Column('supply_unit_description', sa.Text(), nullable=True),
    sa.Column('measure_unit_acronym', sa.String(length=20), nullable=True),
    sa.Column('measure_unit_capacity', sa.String(length=50), nullable=True),
    sa.Column('supply_unit_pdm_status', sa.Boolean(), nullable=True),
    sa.Column('supply_unit_status', sa.Boolean(), nullable=True),
    sa.Column('supply_unit_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pdm_code'], ['pdms.pdm_code'], name=op.f('fk_supply_units_pdm_code_pdms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pdm_code', 'supply_unit_sequence', name=op.f('pk_supply_units'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_units')
    op.drop_index(op.f('ix_pdm_expense_natures_expense_nature_code'), table_name='pdm_expense_natures')
    op.drop_table('pdm_expense_natures')
    op.drop_index('ix_items_status_active', table_name='items')
    op.drop_index(op.f('ix_items_pdm_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_pdms_class_code'), table_name='pdms')
    op.drop_table('pdms')
    op.drop_index(op.f('ix_classes_group_code'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('groups')
    op.drop_table('expense_natures')
    # ### end Alembic commands ###
