"""add content_hash to items

Revision ID: 8e2a1b76a055
Revises: 124e6804b003
Create Date: 2026-09-17 15:21:19.126387

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e2a1b76a055'
down_revision: str | Sequence[str] | None = '124e6804b003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'content_hash')
    # ### end Alembic commands ###
